spring:
  datasource:
    initialization-mode: always
    platform: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true

vault:
  appconfig:
    token: ${TOKEN:default}
